
@url = http://localhost:8080/cart
//@url = https://cartserviceem.azurewebsites.net/cart


GET {{url}}

###

GET {{url}}/1

###




POST {{url}}/
Content-Type: application/json

{

    "user_id": 1212,
    "product": "kamel",
    "quantity": 3,
    "price": 150
}

###


PATCH {{url}}/6
Content-Type: application/json

{

    "user_id": 1212,
    "product": "kamel",
    "quantity": 4,
    "price": 150
}


###
DELETE {{url}}/6
