
@url = http://localhost:3000


GET {{url}}/cart

###

GET {{url}}/cart/123

###




POST {{url}}/products
Content-Type: application/json

{
    "customerid": "124",
    "product": "kamel",
    "amount": 1,
    "price": 12
}