
//@url = http://localhost:8080/cart
@url = https://cartserviceem.azurewebsites.net/cart
@token = {{$dotenv TOKEN}}


GET {{url}}

###

GET {{url}}/1

###




POST {{url}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{

    "user_id": 124,
    "product": "kamel",
    "quantity": 7,
    "price": 1544
}

###


PATCH {{url}}/13
Authorization: Bearer {{token}}
Content-Type: application/json

{

    "user_id": 124,
    "product": "kamel",
    "quantity": 8,
    "price": 1600
}


###
DELETE {{url}}/13
Authorization: Bearer {{token}}